/**
 * `clihub ci` generator (v1.1.0).
 *
 * Emits a ready-to-commit CI config that validates clihub.yaml and gates
 * config drift on every push — turnkey adoption for the apply/lock/status
 * workflow. The default checks are lightweight (no CLI installs in CI):
 *
 *   - clihub apply --plan          → clihub.yaml parses + resolves
 *   - clihub memory generate --check (commented; enable if you commit
 *     generated memory files)
 *   - clihub status --strict       (commented; enable if CI installs the
 *     CLIs so versions can be compared to the lockfile)
 *
 * Pure string generation; no new dependencies.
 */

export type CiProvider = 'github' | 'gitlab';

export const CI_PROVIDERS: CiProvider[] = ['github', 'gitlab'];

export interface CiOpts {
  /** Node version for the runner (default '20'). */
  nodeVersion?: string;
  /** npm package to install (default '@wikieden/clihub'). */
  pkg?: string;
}

/** Conventional output path for a provider's config. */
export function defaultCiPath(provider: CiProvider): string {
  return provider === 'github' ? '.github/workflows/clihub.yml' : '.gitlab-ci.clihub.yml';
}

function githubWorkflow(node: string, pkg: string): string {
  return `# Generated by \`clihub ci\`. Verifies clihub.yaml on every push.
name: clihub
on:
  push:
  pull_request:
jobs:
  clihub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${node}'
      - name: Install clihub
        run: npm install -g ${pkg}
      - name: Validate clihub.yaml
        run: clihub apply --plan
      # Enable if you commit generated memory files (CLAUDE.md, AGENTS.md, ...):
      # - name: Memory in sync
      #   run: clihub memory generate --all --check
      # Enable if this job also installs the CLIs (so versions can be checked):
      # - name: Toolchain matches clihub.lock.json
      #   run: clihub status --strict
`;
}

function gitlabWorkflow(node: string, pkg: string): string {
  return `# Generated by \`clihub ci\`. Include in .gitlab-ci.yml.
clihub:
  image: node:${node}
  script:
    - npm install -g ${pkg}
    - clihub apply --plan
    # - clihub memory generate --all --check
    # - clihub status --strict
`;
}

export function ciWorkflow(provider: CiProvider, opts: CiOpts = {}): string {
  const node = opts.nodeVersion ?? '20';
  const pkg = opts.pkg ?? '@wikieden/clihub';
  return provider === 'github' ? githubWorkflow(node, pkg) : gitlabWorkflow(node, pkg);
}
