/**
 * `clihub pack` generator (v1.4.0, Pillar VI — reach).
 *
 * Emits distribution manifests so clihub can be installed beyond npm:
 *
 *   - docker → a Dockerfile (`docker build` → runnable clihub image)
 *   - brew   → a Homebrew formula (fill the sha256 at tap time)
 *   - scoop  → a Scoop manifest (Windows)
 *
 * Pure string generation; no new dependencies. brew/scoop carry a
 * `__FILL_SHA256__` placeholder — the maintainer fills it from the
 * published npm tarball when updating the tap/bucket (standard flow).
 */

export type PackTarget = 'docker' | 'brew' | 'scoop';

export const PACK_TARGETS: PackTarget[] = ['docker', 'brew', 'scoop'];

export interface PackOpts {
  /** Package version (no leading v). */
  version: string;
  /** npm package name (default '@wikieden/clihub'). */
  pkg?: string;
  /** Node version for the Docker base image (default '20'). */
  nodeVersion?: string;
}

const DESC = 'Install & sync AI coding CLIs (Claude Code, Codex, Gemini, Kiro, Cursor, Goose)';
const HOMEPAGE = 'https://github.com/wikieden/clihub';

function dockerfile(pkg: string, version: string, node: string): string {
  return `# Generated by \`clihub pack docker\`.
FROM node:${node}-alpine
LABEL org.opencontainers.image.source="${HOMEPAGE}"
LABEL org.opencontainers.image.description="${DESC}"
RUN npm install -g ${pkg}@${version}
ENTRYPOINT ["clihub"]
CMD ["--help"]
`;
}

function brewFormula(pkg: string, version: string): string {
  return `# Generated by \`clihub pack brew\`. Fill sha256 from the npm tarball.
class Clihub < Formula
  desc "${DESC}"
  homepage "${HOMEPAGE}"
  url "https://registry.npmjs.org/${pkg}/-/${pkg.split('/').pop()}-${version}.tgz"
  sha256 "__FILL_SHA256__"
  license "MIT"
  depends_on "node"

  def install
    system "npm", "install", "-g", "--prefix=#{libexec}", "${pkg}@#{version}"
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match "clihub/", shell_output("#{bin}/clihub --version")
  end
end
`;
}

function scoopManifest(pkg: string, version: string): string {
  return JSON.stringify(
    {
      version,
      description: DESC,
      homepage: HOMEPAGE,
      license: 'MIT',
      depends: 'nodejs',
      suggest: { Node: 'nodejs' },
      installer: { script: `npm install -g ${pkg}@${version}` },
      uninstaller: { script: `npm uninstall -g ${pkg}` },
      bin: 'clihub',
      checkver: { url: `https://registry.npmjs.org/${pkg}/latest`, jsonpath: '$.version' },
    },
    null,
    2,
  ) + '\n';
}

export function packManifest(target: PackTarget, opts: PackOpts): string {
  const pkg = opts.pkg ?? '@wikieden/clihub';
  const node = opts.nodeVersion ?? '20';
  switch (target) {
    case 'docker':
      return dockerfile(pkg, opts.version, node);
    case 'brew':
      return brewFormula(pkg, opts.version);
    case 'scoop':
      return scoopManifest(pkg, opts.version);
    default:
      throw new Error(`unknown pack target: ${target as string}`);
  }
}
